### ISSUE TITLE
XenoWorldReset, version 2.1.3, does not work with Paper 1.21

### ISSUE THREAD

**Issue by VimaMT** [CroaBeast/SIR_Plugin#12]
I am using the latest version of Paper 1.21, as of this date.
I am using XenoWorldReset, version 2.1.3.
The description on Spigot states that this version should support 1.21.

Message in console:  XWR v2.1.3 does not support 1.21.x and newer. Please update!

I am unable to access any XWR commands after startup.

**Comment by CroaBeast** [comment]
Hi, this is not the GitHub for XWR. Currently, XWR does not have a public repository.

**Comment by Klema4** [comment]
Please join our Discord or install the newest release on Spigot. We'll discuss it [there](https://discord.gg/57mJCfchzs) instead.
