### ISSUE TITLE
NoSuchMethodError in XenoWorldReset plugin on Paper 1.21.1

### ISSUE THREAD

**Issue by v4r1n** [CroaBeast/SIR_Plugin#13]
**Describe the bug**
The XenoWorldReset plugin throws a `NoSuchMethodError` when interacting with a player head item in the XWR GUI menu. The issue occurs when the server tries to handle an inventory click event. The error seems to be related to a missing or outdated method `(getBukkitView())` in the plugin's AnvilContainer class, causing the plugin to fail on Paper 1.21.1

**Expected Behavior**
The XWR menu should open successfully when the command `/xwr menu` is used, and all interactions with the GUI should function without errors.

**Actual Behavior**
Upon interacting with slot 13 (player head) in the XWR Worlds menu, the server throws a NoSuchMethodError and the action cannot be completed. The exact error log is as follows:
```
[19:23:36 ERROR]: [XWR] Exception while handling click event in inventory 'XWR | Worlds', slot=13, item=PLAYER_HEAD
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView net.zerotoil.mc.xenoworldreset.gui.anvil.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'
...
```

**Steps to Reproduce**
Run Paper 1.21.1 server.
Install XenoWorldReset version 2.1.3.
Use the /xwr menu command.
Click on the player head in slot 13 of the Worlds menu.
The error occurs and the interaction fails.

**Plugin List**
Paper Plugins:
    TheNewEconomy (0.1.3.2)
    Bukkit Plugins:
    AuraSkills (2.2.3)
    Bookshelf (3.1.10.0)
    CMI (9.7.6.1)
    CMILib (1.5.1.3)
    Citizens (2.0.35-SNAPSHOT)
    CustomCrops (3.6.6)
    CustomNameplates (2.4.8.1)
    DeluxeMenus (1.14.1-DEV-184)
    FastAsyncWorldEdit (2.11.2-SNAPSHOT-894)
    LuckPerms (5.4.141)
    Multiverse-Core (4.3.13-SNAPSHOT)
    Oraxen (1.181.0)
    Pl-Hide-Pro (2.10.4)
    PlaceholderAPI (2.11.7-DEV-200)
    PluginManagerPlus (2.7.11)
    ProtectionLib (1.8.4)
    ProtocolLib (5.3.0-SNAPSHOT-726)
    RealisticSeasons (11.2.1)
    SSX-Connector (2.2.2-beta)
    TAB-Bridge (5.0.7)
    TimeManager (1.9.1)
    Vault (2.5.0)
    VoidTeleportPlus (3.5.5)
    WorldGuard (7.0.11-SNAPSHOT)
    WorldGuardExtraFlags (4.2.5-SNAPSHOT)
    XenoWorldReset (2.1.3)
    packetevents (2.5.0)

**Additional Information**
None at the moment, but please let me know if you need more details.

**Comment by Klema4** [comment]
This error was already reported, but you are in wrong repository to report bugs.
Join our [Discord server](https://discord.gg/57mJCfchzs) to get help.

**Comment by Kihsomray** [comment]
> **Describe the bug** The XenoWorldReset plugin throws a `NoSuchMethodError` when interacting with a player head item in the XWR GUI menu. The issue occurs when the server tries to handle an inventory click event. The error seems to be related to a missing or outdated method `(getBukkitView())` in the plugin's AnvilContainer class, causing the plugin to fail on Paper 1.21.1
> 
> **Expected Behavior** The XWR menu should open successfully when the command `/xwr menu` is used, and all interactions with the GUI should function without errors.
> 
> **Actual Behavior** Upon interacting with slot 13 (player head) in the XWR Worlds menu, the server throws a NoSuchMethodError and the action cannot be completed. The exact error log is as follows:
> 
> ```
> [19:23:36 ERROR]: [XWR] Exception while handling click event in inventory 'XWR | Worlds', slot=13, item=PLAYER_HEAD
> java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView net.zerotoil.mc.xenoworldreset.gui.anvil.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'
> ...
> ```
> 
> **Steps to Reproduce** Run Paper 1.21.1 server. Install XenoWorldReset version 2.1.3. Use the /xwr menu command. Click on the player head in slot 13 of the Worlds menu. The error occurs and the interaction fails.
> 
> **Plugin List** Paper Plugins: TheNewEconomy (0.1.3.2) Bukkit Plugins: AuraSkills (2.2.3) Bookshelf (3.1.10.0) CMI (9.7.6.1) CMILib (1.5.1.3) Citizens (2.0.35-SNAPSHOT) CustomCrops (3.6.6) CustomNameplates (2.4.8.1) DeluxeMenus (1.14.1-DEV-184) FastAsyncWorldEdit (2.11.2-SNAPSHOT-894) LuckPerms (5.4.141) Multiverse-Core (4.3.13-SNAPSHOT) Oraxen (1.181.0) Pl-Hide-Pro (2.10.4) PlaceholderAPI (2.11.7-DEV-200) PluginManagerPlus (2.7.11) ProtectionLib (1.8.4) ProtocolLib (5.3.0-SNAPSHOT-726) RealisticSeasons (11.2.1) SSX-Connector (2.2.2-beta) TAB-Bridge (5.0.7) TimeManager (1.9.1) Vault (2.5.0) VoidTeleportPlus (3.5.5) WorldGuard (7.0.11-SNAPSHOT) WorldGuardExtraFlags (4.2.5-SNAPSHOT) XenoWorldReset (2.1.3) packetevents (2.5.0)
> 
> **Additional Information** None at the moment, but please let me know if you need more details.

Fixed 👍
