### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by Trinchezito** [CroaBeast/SIR_Plugin#2]
When someone types the % chat the RGB colors stops working.

![image](https://user-images.githubusercontent.com/98068350/151354792-11126dcc-c651-4122-a2f5-ca5fed7a9fd1.png)

**Comment by CroaBeast** [comment]
Hi, can you send me your chat.yml file?
Also, send any errors in the console and the exact chat message you are typing to duplicate that issue.

**Comment by Trinchezito** [comment]
My chat.config is as follow: https://pastebin.com/raw/FBTXqgTq

Unfortunately, there are no errors in the console :( It seems to only happen when the % symbol is written first or last. 
![image](https://user-images.githubusercontent.com/98068350/151377229-122056dc-80da-4dac-8bd2-4100dd4a9b8e.png)
![image](https://user-images.githubusercontent.com/98068350/151377328-bfd5076a-b3f3-420b-aba1-0f2a172044d2.png)

**Comment by CroaBeast** [comment]
I think I know the problem, but currently I'm recoding (again) SIR, bc my code was really messy. If you want to test a dev build that will solve that issue, please join our discord server :D

**Comment by CroaBeast** [comment]
btw, this issue is fixed in the recode version
I forgot to close this issue xdd
