### ISSUE TITLE
Add GitHub Actions for Bleeding Edge builds

### ISSUE THREAD

**Issue by CamperSamu** [CroaBeast/SIR_Plugin#3]
https://www.spigotmc.org/threads/automating-your-stuff-with-github-actions.496489/

This can be useful for allowing users to test bleeding edge builds and possibly discover bugs before release.

**Comment by CroaBeast** [comment]
That's interesting, gonna look at it when I have time.

**Comment by CroaBeast** [comment]
@CamperSamu I made this action but I still don't get how that works.
So you can check it out: [https://github.com/CroaBeast/SIR_Plugin/runs/5980314210?check_suite_focus=true](https://github.com/CroaBeast/SIR_Plugin/runs/5980314210?check_suite_focus=true)

**Comment by CamperSamu** [comment]
Hm, it's late where I live so I don't have the time to check it out now, but I'll be checking the action yml tomorrow, maybe I can figure it out.
Thanks for the reply!

**Comment by CroaBeast** [comment]
Hi, I'm gonna get rid of GitHub actions. Idk how that works or even make it work right. Sorry bud
