### ISSUE TITLE
JSON formatting in formats.yml?

### ISSUE THREAD

**Issue by ghost** [CroaBeast/SIR_Plugin#4]
The description of the plugin on spigotmc.com says that the plugin supports raw JSON chat formatting, but as far as I understand, this only works in certain places, for example, in announces.yml and join-quit.yml, but for the chat format itself for different groups in formats.yml doesn't work, or am I doing something wrong?
https://i.imgur.com/hIQxyWr.png
https://i.imgur.com/CLCyvZP.png

If it really doesn't work at the moment, then what's the problem with adding this feature? In any case, you already have some kind of JSON support for some types of messages, so why not make this for **whole** chat?

**Comment by CroaBeast** [comment]
It has support for JSON formats, but in a sort of MiniMessage format, the thing is that I don't have a full wiki of SIR to explain all the features, bc I don't have enough time of doing that.
You can use this in your format:
- '<hover=[my hover text<n>a new line]>{player}:</text> {message}'

**Comment by ghost** [comment]
> It has support for JSON formats, but in a sort of MiniMessage format, the thing is that I don't have a full wiki of SIR to explain all the features, bc I don't have enough time of doing that. You can use this in your format:
> 
> * '<hover=[my hover texta new line]>{player}: {message}'

It's certainly cool. But it will be even cooler if you add support for raw json. I don't understand why if the plugin supports raw json I have to use a castrated MiniMessage. Just add it. And there will be no replacement for your plugin. I have not found a single plugin for Spigot that supports full json formatting.

**Comment by CroaBeast** [comment]
Gonna close this issue. The last Spigot version and new dev build has the feature to use JSON Minecraft format in chat formatting.
Just put the `[JSON]` key before in your format section and that's all.
