### ISSUE TITLE
about the servers in the spigot readme!

### ISSUE THREAD

**Issue by sebastianjnuwu** [CroaBeast/SIR_Plugin#6]
I noticed that 2 of the 3 servers that are in the plugin's readme are offline, how or what criteria do you put a server there?

**Comment by CroaBeast** [comment]
Hi! I put them very long ago.
I ask the owners a screeenshot of its plugin list if they have SIR installed, that's all.
I didn't want to put more servers because the spigot page need a complete rework.

**Comment by sebastianjnuwu** [comment]
> Hi! I put them very long ago. I ask the owners a screeenshot of its plugin list if they have SIR installed, that's all. I didn't want to put more servers because the spigot page need a complete rework.

I understand, it's because as I said before there are offline servers and it gets ugly....
