### ISSUE TITLE
Cast problem about advancement values

### ISSUE THREAD

**Issue by Galaxy-VN** [CroaBeast/SIR_Plugin#8]
So after startup server done the plugin start up 
``[SIR] Registering all the advancement values...``

And i got a warning like this https://paste.helpch.at/rorosaqezi.scss

Server Version: 1.19.4
Software: Purpur

**Comment by CroaBeast** [comment]
Sorry about the late response. 

I officially release a dev build in the [SIR Discord server](https://discord.gg/XBTDvVA8XR), if you want the file, you can download it there.
